### ISSUE TITLE
The updatesite link is broken

### ISSUE THREAD

**Issue by jurneo** [szschaler/GridGames#10]
This link is broken:
https://szschaler.github.io/GridGames/updatesite/

**Comment by szschaler** [comment]
That seems to be true. Will check what's going on asap.

**Comment by szschaler** [comment]
Just checked: the link isn't actually broken. It just doesn't contain any "website", so when you simply click on the link GitHub will show a 404. However, you can use it as normal as an update site in Eclipse: https://marketplace.eclipse.org/content/swt-win32-extension/help. I will add this information to the README.
